---
# Config variables
ghidra_file_url: "https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.3.3_build/ghidra_10.3.3_PUBLIC_20230829.zip"
ghidra_file_checksum: "sha256:63833361bea8ef5ada1bc28cd2aa2ae4ab43204d2672b595500372582152eebe"
ghidra_installation_directory: "{{ ansible_env.HOME + '/ghidra' }}"
ghidra_jdk_package: "openjdk-17-jdk"

# Calculated variables from config
ghidra_download_target: "{{ ghidra_installation_directory + '/' + (file_url | basename) }}"
